### ISSUE TITLE
No tests exist for contracts

### ISSUE THREAD

**Issue by Pafaul** [sunswapteam/sunswap2.0-contracts#3]
So there is badge that states that tests are passing, but there are no tests performed on contracts, just compilation and no traces of ```test``` command is found. 
This means that new version of contracts aren't tested.

Badge:
![image](https://user-images.githubusercontent.com/18599919/196700293-f6948f91-0f06-4a77-83e9-b31f00e84308.png)

Commented test command in github workflow:
![image](https://user-images.githubusercontent.com/18599919/196700423-d0238286-607d-4194-b6e6-696ac37d8e4e.png)

Link to github workflow: [Line with commented tests](https://github.com/sunswapteam/sunswap2.0-contracts/blob/2df7e0b968d9304c8ad1089c181075f9eca5e20d/.github/workflows/tests.yml#L36)

Package.json without test command:  [no test script in package.json](https://github.com/sunswapteam/sunswap2.0-contracts/blob/2df7e0b968d9304c8ad1089c181075f9eca5e20d/package.json#L4)

**Comment by fantastic-air** [comment]
Thanks for your attention, actually we are working on it and will release our test cases soon.
Also we are looking forward for contributions.

**Comment by fantastic-air** [comment]
@Pafaul [v1.1.0](https://github.com/sunswapteam/sunswap2.0-contracts/releases/tag/v1.1.0) has been released. I'm closing this issue.
